service: cloud-crm-data-recovery-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    CRM_CONTACTS_TABLE_ARN: ${cf:perfsys-cloud-crm-api-dev.ContactsTable}
    CRM_UPDATES_TABLE_ARN: ${cf:perfsys-cloud-crm-api-dev.UpdatesTable}
    CRM_GROUPS_TABLE_ARN: ${cf:perfsys-cloud-crm-api-dev.GroupsTable}
    CRM_COMPANIES_TABLE_ARN: ${cf:perfsys-cloud-crm-api-dev.CompaniesTable}
    UNIVERSAL_STORAGE_ARN:
      Fn::GetAtt:
        - Bucket
        - Arn
  iamRoleStatements:
    -
      Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - ${self:provider.environment.CRM_CONTACTS_TABLE_ARN}
        - ${self:provider.environment.CRM_UPDATES_TABLE_ARN}
        - ${self:provider.environment.CRM_GROUPS_TABLE_ARN}
        - ${self:provider.environment.CRM_COMPANIES_TABLE_ARN}
    -
      Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        "Fn::Join":
          - ''
          -
            - { "Fn::GetAtt": ["Bucket", "Arn" ] }
            - '/*'

functions:

  plugin-1:
    handler: index.handler
    events:
      - schedule:
          description: Performing scheduled logging
          rate: rate(8 hours)

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: universal-storage
